"use client";
import Link from "next/link";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,Coffee,Gift,UtensilsCrossed,Check,Ticket,Coins} from "lucide-react";
import type {Wallet,Product} from "@/lib/credits";
import {buyVoucher,redeemVoucher} from "@/app/credit-actions";
import {Button} from "./ui/Button";
export function Rewards({wallet,products}:{wallet:Wallet;products:Product[]}){
 const [selection,setSelection]=useState<Product|null>(null);const [useId,setUseId]=useState<string|null>(null);const [request,setRequest]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [pending,start]=useTransition();const router=useRouter();
 function buy(){if(!selection)return;setError("");start(async()=>{const r=await buyVoucher(selection.id,request);if(!r.ok){setError(r.error);return;}setSelection(null);setNotice("시연 이용권을 받았어요. 내 이용권에서 확인해 주세요.");router.refresh();});}
 function use(){if(!useId)return;setError("");start(async()=>{const r=await redeemVoucher(useId);if(!r.ok){setError(r.error);return;}setUseId(null);setNotice("사용 완료를 시연했어요. 실제 매장에서는 사용할 수 없어요.");router.refresh();});}
 return <div className="space-y-6 px-5 pb-8"><div><p className="mb-2 text-xs font-semibold text-primary">동네에서 쓰는 작은 보상</p><h1 className="text-[28px] font-bold tracking-tight">내 생각이 동네 혜택으로</h1><p className="mt-2 text-xs leading-6 text-muted-foreground">참여하며 모은 크레딧으로 이용권을 교환해 보세요.</p></div>
  <section className="rounded-3xl bg-primary p-6 text-white"><p className="text-xs text-white/80">내가 모은 크레딧</p><p className="mt-3 flex items-baseline gap-2 text-[42px] font-bold tracking-tight">{wallet.balance.toLocaleString()}<span className="text-lg">C</span></p><Link href="/" className="mt-4 inline-flex min-h-10 items-center gap-2 text-xs font-semibold">아이디어에 생각 더하고 모으기<ArrowRight className="size-4"/></Link></section>
  <p className="rounded-xl border border-[var(--brand-paper-border)] bg-[var(--brand-paper)] p-3 text-[11px] leading-5 text-muted-foreground">모든 매장은 가상의 시연 매장입니다. 크레딧은 현금 가치가 없으며, 이용권은 실제 결제·식사·매장 사용을 지원하지 않습니다.</p>
  {notice&&<p role="status" className="rounded-xl bg-primary/5 p-3 text-xs text-primary">{notice}</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
  <section><h2 className="mb-4 text-lg font-bold">동네 혜택 둘러보기</h2><div className="space-y-3">{products.map(p=><article key={p.id} className="rounded-2xl border border-border p-4"><div className="flex gap-4"><div className="flex size-16 shrink-0 items-center justify-center rounded-xl bg-[var(--brand-soft)] text-primary">{p.id==="coffee"?<Coffee className="size-7"/>:p.id==="meal"?<UtensilsCrossed className="size-7"/>:<Gift className="size-7"/>}</div><div className="min-w-0"><p className="text-[10px] text-muted-foreground">{p.shop}</p><h3 className="mt-1 text-base font-semibold">{p.title}</h3><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{p.detail}</p></div></div><div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1.5 text-sm font-bold text-primary"><Coins className="size-4"/>{p.cost} C</span><Button size="sm" disabled={!wallet.enabled||wallet.balance<p.cost||pending} onClick={()=>{setSelection(p);setRequest(crypto.randomUUID());setError("");}}>{wallet.balance<p.cost?`${p.cost-wallet.balance}C 더 모으면` : "이용권 교환"}</Button></div></article>)}</div></section>
  {selection&&<section aria-labelledby="purchase-title" className="rounded-2xl border-2 border-primary bg-[var(--brand-soft)] p-4"><h2 id="purchase-title" className="font-bold">{selection.title}으로 교환할까요?</h2><p className="mt-2 text-xs leading-6">{selection.cost}C가 차감돼요. 교환 후 잔액은 {wallet.balance-selection.cost}C예요.<br/>실제 매장에서는 사용할 수 없는 시연용 이용권입니다.</p><div className="mt-3 flex gap-2"><Button disabled={pending} onClick={buy}>{pending?"교환 중…":"교환 확정"}</Button><Button variant="outline" disabled={pending} onClick={()=>setSelection(null)}>취소</Button></div></section>}
  <section><h2 className="mb-4 text-lg font-bold">내 이용권 <span className="text-primary">{wallet.vouchers.filter(v=>!v.usedAt).length}</span></h2>{wallet.vouchers.length?<div className="space-y-3">{wallet.vouchers.map(v=><article key={v.id} className="rounded-2xl border border-dashed border-[var(--brand-paper-border)] bg-[var(--brand-paper)] p-4"><div className="flex items-center gap-3"><Ticket className="size-6 shrink-0 text-primary"/><div><h3 className="text-sm font-semibold">{v.title}</h3><p className="mt-1 text-[10px] text-muted-foreground">DEMO · 실제 매장 사용 불가</p></div></div><p className="mt-3 font-mono text-[11px] text-muted-foreground">시연 코드 {v.id.toUpperCase()}</p>{v.usedAt?<p className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground"><Check className="size-4"/>시연 사용 완료</p>:useId===v.id?<div className="mt-3"><p className="text-xs">시연용 사용 완료 상태로 바꿀까요?</p><div className="mt-2 flex gap-2"><Button size="sm" disabled={pending} onClick={use}>시연 사용 확정</Button><Button variant="outline" size="sm" disabled={pending} onClick={()=>setUseId(null)}>취소</Button></div></div>:<Button variant="outline" size="sm" disabled={pending} className="mt-3" onClick={()=>setUseId(v.id)}>사용 과정 시연</Button>}</article>)}</div>:<p className="rounded-xl bg-muted/50 p-5 text-xs leading-6 text-muted-foreground">아직 이용권이 없어요. 아이디어에 참여해 크레딧을 모아보세요.</p>}</section>
  <section><h2 className="mb-3 text-lg font-bold">크레딧 기록</h2>{wallet.ledger.length?<ul className="divide-y divide-border">{wallet.ledger.map((r,i)=><li key={`${r.createdAt}-${i}`} className="flex items-start justify-between gap-3 py-3"><div><p className="text-xs leading-5">{r.description}</p><time className="text-[10px] text-muted-foreground">{new Date(r.createdAt).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})}</time></div><span className={`shrink-0 text-sm font-bold ${r.amount>0?"text-primary":"text-muted-foreground"}`}>{r.amount>0?"+":""}{r.amount}C</span></li>)}</ul>:<p className="text-xs text-muted-foreground">참여와 교환 기록이 여기에 쌓여요.</p>}</section>
 </div>;
}
