"use client";
import Link from "next/link";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {ArrowUpRight,Coins,Heart,MessageCircle,Plus,Wallet,X} from "lucide-react";
import type {Team} from "@/lib/credits";
import {endIdea,fundIdea,topupCredits} from "@/app/credit-actions";
import {Button} from "./ui/Button";
import {Input} from "./ui/Input";
export function TeamSpace({initial}:{initial:Team}){
 const [pending,start]=useTransition();const [error,setError]=useState("");const [notice,setNotice]=useState("");const [ending,setEnding]=useState<string|null>(null);const [amounts,setAmounts]=useState<Record<string,string>>({});const router=useRouter();
 function topup(amount:number){setError("");start(async()=>{const r=await topupCredits(amount);if(!r.ok){setError(r.error);return;}setNotice(`${amount.toLocaleString()}C를 시연 충전했어요. 실제 결제는 발생하지 않습니다.`);router.refresh();});}
 function end(id:string){setError("");start(async()=>{const r=await endIdea(id);if(!r.ok){setError(r.error);return;}setEnding(null);setNotice(`모집을 마감하고 남은 예산 ${r.data.returned}C를 돌려받았어요. 관리 화면에서 리포트와 결론을 공개해 주세요.`);router.refresh();});}
 function fund(id:string){setError("");start(async()=>{const r=await fundIdea(id,Number(amounts[id]??"300"));if(!r.ok){setError(r.error);return;}setNotice("아이디어의 참여 보상 예산을 배정했어요.");router.refresh();});}
 return <div className="space-y-6 px-5 pb-8"><div><p className="mb-2 text-xs font-semibold text-primary">생각을 의뢰하는 팀을 위해</p><h1 className="text-[28px] font-bold tracking-tight">우리 팀의 아이디어</h1><p className="mt-2 text-xs leading-6 text-muted-foreground">예산을 준비하고, 주민의 솔직한 생각을 만나보세요.</p></div>
  <section className="rounded-3xl border border-[var(--brand-paper-border)] bg-[var(--brand-paper)] p-5"><p className="flex items-center gap-2 text-xs text-muted-foreground"><Wallet className="size-4"/>우리 팀의 참여 보상 예산</p><p className="mt-3 text-[34px] font-bold text-primary">{initial.balance.toLocaleString()}<span className="ml-2 text-base">C</span></p><div className="mt-4 grid grid-cols-2 gap-2"><Button disabled={pending||!initial.enabled} onClick={()=>topup(500)}>500C 시연 충전</Button><Button variant="outline" disabled={pending||!initial.enabled} onClick={()=>topup(1000)}>1,000C 충전</Button></div><p className="mt-3 text-[10px] leading-5 text-muted-foreground">실제 결제 없이 팀 예산 지갑에만 충전돼요. 참여 보상 지갑과 분리되며, 예산 배정 시 차감되고, 참여할 때만 예산이 사용됩니다.</p></section>
  <div className="grid grid-cols-3 gap-2 text-center text-[10px] text-muted-foreground"><p className="rounded-xl bg-muted/60 py-3">1. 시연 충전</p><p className="rounded-xl bg-muted/60 py-3">2. 카드·예산 준비</p><p className="rounded-xl bg-muted/60 py-3">3. 반응·이유 확인</p></div>
  <Button asChild className="w-full"><Link href="/new"><Plus/>새 아이디어 올리기</Link></Button>
  {error&&<p role="alert" className="rounded-xl bg-destructive/5 p-3 text-xs text-destructive">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-primary/5 p-3 text-xs text-primary">{notice}</p>}
  {initial.campaigns.length?initial.campaigns.map(c=>{const open=c.open;return <section key={c.id} className="rounded-2xl border border-border p-4"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-bold leading-7">{c.title}</h2>{!c.hidden&&<Link className="flex min-h-10 shrink-0 items-center gap-1 text-[11px] text-primary" href={`/cards/${c.id}`}>관리<ArrowUpRight className="size-3"/></Link>}</div><p className="mt-1 text-[10px] text-muted-foreground">{c.hidden?"운영자가 숨긴 카드 · 미사용 예산 반환 가능":open?(c.remaining>=30?"주민에게 공개 중":"예산 배정 후 발견에 표시돼요"):"참여 종료"}</p><div className="my-4 grid grid-cols-3 gap-2"><div className="rounded-xl bg-[var(--brand-soft)] p-3"><p className="text-[10px] text-muted-foreground">남은 예산</p><p className="mt-1 text-lg font-bold text-primary">{c.remaining}C</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="flex items-center gap-1 text-[10px] text-muted-foreground"><Heart className="size-3"/>관심</p><p className="mt-1 text-lg font-bold">{c.likes}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="flex items-center gap-1 text-[10px] text-muted-foreground"><X className="size-3"/>패스</p><p className="mt-1 text-lg font-bold">{c.passes}</p></div></div><p className="text-[10px] text-muted-foreground">배정 {c.funded}C · 지급 {c.funded-c.remaining-c.returned}C · 반환 {c.returned}C · 최대 보상 30C/카드/기기</p>
   {open&&<div className="mt-4"><label htmlFor={`fund-${c.id}`} className="mb-2 block text-xs font-semibold">참여 보상 예산 추가</label><div className="flex gap-2"><Input id={`fund-${c.id}`} type="number" min={30} max={10000} step={10} value={amounts[c.id]??"300"} onChange={e=>setAmounts(a=>({...a,[c.id]:e.target.value}))} className="min-w-0 flex-1"/><Button disabled={pending} onClick={()=>fund(c.id)}><Coins className="size-4"/>배정</Button></div><p className="mt-2 text-[10px] text-muted-foreground">300C는 이유 포함 최대 10개의 응답 예산이에요.</p></div>}
   {(open||c.remaining>0)&&<div className="mt-4">{ending===c.id?<div className="rounded-xl bg-muted p-3"><p className="text-xs leading-6">새 참여를 종료하고 남은 {c.remaining}C를 지갑으로 반환할까요?</p><div className="mt-2 flex gap-2"><Button size="sm" disabled={pending} onClick={()=>end(c.id)}>마감 확정</Button><Button size="sm" variant="outline" disabled={pending} onClick={()=>setEnding(null)}>취소</Button></div></div>:<Button size="sm" variant="outline" disabled={pending} onClick={()=>setEnding(c.id)}>{open?"모집 마감·남은 예산 반환":"남은 예산 반환"}</Button>}</div>}
   <details className="mt-5 border-t border-border pt-4"><summary className="cursor-pointer text-xs font-semibold">참여자가 남긴 이유 ({c.responses.filter(r=>r.reason).length})</summary><div className="mt-3 space-y-3">{c.responses.filter(r=>r.reason).map((r,i)=><div key={i} className="rounded-xl bg-muted/50 p-3"><p className="mb-1 flex items-center gap-1 text-[10px] font-semibold text-primary"><MessageCircle className="size-3"/>{r.direction==="RIGHT"?"관심 있어요":"이번엔 패스"}</p><p className="text-xs leading-6">{r.reason}</p></div>)}{!c.responses.some(r=>r.reason)&&<p className="text-xs text-muted-foreground">아직 이유가 남겨지지 않았어요.</p>}</div></details>
  </section>;}):<div className="rounded-2xl border border-dashed border-border p-6 text-center"><h2 className="font-semibold">첫 아이디어를 준비해 보세요</h2><p className="mt-3 text-xs leading-6 text-muted-foreground">아이디어를 올린 뒤 참여 보상 예산을 배정하면<br/>이웃의 발견 화면에 카드가 나타나요.</p></div>}
  {!!initial.ledger?.length&&<section><h2 className="mb-3 text-lg font-bold">팀 예산 기록</h2><ul className="divide-y divide-border">{initial.ledger.map((r,i)=><li key={`${r.createdAt}-${i}`} className="flex justify-between gap-3 py-3"><p className="text-xs leading-5">{r.description}</p><span className="shrink-0 text-xs font-semibold text-primary">{r.amount>0?"+":""}{r.amount}C</span></li>)}</ul></section>}
  <p className="text-[10px] leading-5 text-muted-foreground">기기 단위의 비공식 반응입니다. 관심이 실제 구매 의향을 뜻하지 않으며, 보상 참여가 응답에 영향을 줄 수 있어요. 미사용 예산은 마감 시 지갑으로 돌아옵니다. 실제 결제와 매장 정산은 이번 시연에 포함되지 않습니다.</p><Link href="/admin" className="inline-flex min-h-10 items-center text-xs text-muted-foreground">운영자 공간</Link>
 </div>;
}
